CREATE TABLE visits (
	id INT(11) NOT NULL AUTO_INCREMENT,
	kiosk VARCHAR(20) NULL DEFAULT NULL,
	visit_date DATETIME NULL DEFAULT NULL,
	user_name VARCHAR(200) NULL DEFAULT NULL,
	device VARCHAR(200) NULL DEFAULT NULL,
	PRIMARY KEY (id)
);